#ifndef __NIGHT_LIGHT_PARAM_H__
#define __NIGHT_LIGHT_PARAM_H__

#define LIGHTNESS_WEAK_DUTY 25
#define LIGHTNESS_MID_DUTY  50
#define LIGHTNESS_HIGHT_DUTY 99
#define LIGHTDELAYSHORT 1000
#define LIGHTDELAYMID 2000
#define LIGHTDELAYLONG 3000

#endif // __NIGHT_LIGHT_PARAM_H__