/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License,Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * 首页 “日程”tab子页面
 */
@Component
export struct ScheduleComponent {
  build() {
    Column() {
      // 头部
      Flex({ alignItems: ItemAlign.Center, justifyContent: FlexAlign.Start }) {
        Text($r("app.string.familyScence")).fontSize(18).margin({ left: 14 }).flexGrow(1)
        Image($r("app.media.icon_search")).width(24).height(24).margin({ right: 18 })
        Image($r("app.media.icon_add")).width(24).height(24).margin({ right: 25 })
      }.height(56).width('100%').backgroundColor(Color.White)
    }
    .width('100%').height('100%').backgroundColor($r("app.color.backgroud_grey"))
  }
}